server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jujiabao/microservicecloud-config.git
#          uri: git@github.com:jujiabao/microservicecloud-config.git #GitHub上面的git仓库名字


